name: Unit test

on:
#  push:
#    paths:
#      - 'src/**'
#      - 'tests/src/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/src/**'
  workflow_dispatch:

jobs:
  build:
    name: Mold Lib Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Mold Lib
      uses: actions/checkout@v4

    - name: Get Alire v2.1.0
      uses: alire-project/setup-alire@v4

    - name: Build unit tests
      run: |
        cd tests
        alr build --release

    - name: Run Mold Lib unit tests
      run: |
        cd tests
        alr exec ./bin/mold_lib_tests
